version: '3.8'

services:
  chatbox:
    build: .
    container_name: rainkoyi-chatbox
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - chatbox-network

networks:
  chatbox-network:
    driver: bridge
